import type { Metadata } from 'next';
import './globals.css';
import { ReduxProvider } from '@/providers/redux-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-roboto">
      <ReduxProvider>
        <body className={`bg-gray-800`}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
